name: Scheduled Run

on:
  push:
  schedule:
    # At 09:00 （UTC） on workdays
    - cron: '0 9 * * 1-5'

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # or '3.12' if compatible 
    
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools wheel
    
    - name: Install dependencies
      run: |
        pip install --use-pep517 -r requirements.txt
    
    - name: Run script
      run: |
        python index.py
